-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('msghead_pb')


PBMSGHEAD = protobuf.Descriptor();
local PBMSGHEAD_VERSION_FIELD = protobuf.FieldDescriptor();
local PBMSGHEAD_TIME_FIELD = protobuf.FieldDescriptor();
local PBMSGHEAD_MSGACT_FIELD = protobuf.FieldDescriptor();
local PBMSGHEAD_MSGTYPE_FIELD = protobuf.FieldDescriptor();
local PBMSGHEAD_MSGID_FIELD = protobuf.FieldDescriptor();
local PBMSGHEAD_MSGRET_FIELD = protobuf.FieldDescriptor();
local PBMSGHEAD_TOKEN_FIELD = protobuf.FieldDescriptor();
PBMSGEMPTY = protobuf.Descriptor();

PBMSGHEAD_VERSION_FIELD.name = "version"
PBMSGHEAD_VERSION_FIELD.full_name = ".PBMsgHead.version"
PBMSGHEAD_VERSION_FIELD.number = 1
PBMSGHEAD_VERSION_FIELD.index = 0
PBMSGHEAD_VERSION_FIELD.label = 1
PBMSGHEAD_VERSION_FIELD.has_default_value = false
PBMSGHEAD_VERSION_FIELD.default_value = 0
PBMSGHEAD_VERSION_FIELD.type = 5
PBMSGHEAD_VERSION_FIELD.cpp_type = 1

PBMSGHEAD_TIME_FIELD.name = "time"
PBMSGHEAD_TIME_FIELD.full_name = ".PBMsgHead.time"
PBMSGHEAD_TIME_FIELD.number = 2
PBMSGHEAD_TIME_FIELD.index = 1
PBMSGHEAD_TIME_FIELD.label = 1
PBMSGHEAD_TIME_FIELD.has_default_value = false
PBMSGHEAD_TIME_FIELD.default_value = 0
PBMSGHEAD_TIME_FIELD.type = 5
PBMSGHEAD_TIME_FIELD.cpp_type = 1

PBMSGHEAD_MSGACT_FIELD.name = "msgact"
PBMSGHEAD_MSGACT_FIELD.full_name = ".PBMsgHead.msgact"
PBMSGHEAD_MSGACT_FIELD.number = 3
PBMSGHEAD_MSGACT_FIELD.index = 2
PBMSGHEAD_MSGACT_FIELD.label = 1
PBMSGHEAD_MSGACT_FIELD.has_default_value = false
PBMSGHEAD_MSGACT_FIELD.default_value = 0
PBMSGHEAD_MSGACT_FIELD.type = 5
PBMSGHEAD_MSGACT_FIELD.cpp_type = 1

PBMSGHEAD_MSGTYPE_FIELD.name = "msgtype"
PBMSGHEAD_MSGTYPE_FIELD.full_name = ".PBMsgHead.msgtype"
PBMSGHEAD_MSGTYPE_FIELD.number = 4
PBMSGHEAD_MSGTYPE_FIELD.index = 3
PBMSGHEAD_MSGTYPE_FIELD.label = 1
PBMSGHEAD_MSGTYPE_FIELD.has_default_value = false
PBMSGHEAD_MSGTYPE_FIELD.default_value = 0
PBMSGHEAD_MSGTYPE_FIELD.type = 5
PBMSGHEAD_MSGTYPE_FIELD.cpp_type = 1

PBMSGHEAD_MSGID_FIELD.name = "msgid"
PBMSGHEAD_MSGID_FIELD.full_name = ".PBMsgHead.msgid"
PBMSGHEAD_MSGID_FIELD.number = 5
PBMSGHEAD_MSGID_FIELD.index = 4
PBMSGHEAD_MSGID_FIELD.label = 1
PBMSGHEAD_MSGID_FIELD.has_default_value = false
PBMSGHEAD_MSGID_FIELD.default_value = 0
PBMSGHEAD_MSGID_FIELD.type = 5
PBMSGHEAD_MSGID_FIELD.cpp_type = 1

PBMSGHEAD_MSGRET_FIELD.name = "msgret"
PBMSGHEAD_MSGRET_FIELD.full_name = ".PBMsgHead.msgret"
PBMSGHEAD_MSGRET_FIELD.number = 6
PBMSGHEAD_MSGRET_FIELD.index = 5
PBMSGHEAD_MSGRET_FIELD.label = 1
PBMSGHEAD_MSGRET_FIELD.has_default_value = false
PBMSGHEAD_MSGRET_FIELD.default_value = 0
PBMSGHEAD_MSGRET_FIELD.type = 5
PBMSGHEAD_MSGRET_FIELD.cpp_type = 1

PBMSGHEAD_TOKEN_FIELD.name = "token"
PBMSGHEAD_TOKEN_FIELD.full_name = ".PBMsgHead.token"
PBMSGHEAD_TOKEN_FIELD.number = 7
PBMSGHEAD_TOKEN_FIELD.index = 6
PBMSGHEAD_TOKEN_FIELD.label = 1
PBMSGHEAD_TOKEN_FIELD.has_default_value = false
PBMSGHEAD_TOKEN_FIELD.default_value = ""
PBMSGHEAD_TOKEN_FIELD.type = 9
PBMSGHEAD_TOKEN_FIELD.cpp_type = 9

PBMSGHEAD.name = "PBMsgHead"
PBMSGHEAD.full_name = ".PBMsgHead"
PBMSGHEAD.nested_types = {}
PBMSGHEAD.enum_types = {}
PBMSGHEAD.fields = {PBMSGHEAD_VERSION_FIELD, PBMSGHEAD_TIME_FIELD, PBMSGHEAD_MSGACT_FIELD, PBMSGHEAD_MSGTYPE_FIELD, PBMSGHEAD_MSGID_FIELD, PBMSGHEAD_MSGRET_FIELD, PBMSGHEAD_TOKEN_FIELD}
PBMSGHEAD.is_extendable = false
PBMSGHEAD.extensions = {}
PBMSGEMPTY.name = "PBMsgEmpty"
PBMSGEMPTY.full_name = ".PBMsgEmpty"
PBMSGEMPTY.nested_types = {}
PBMSGEMPTY.enum_types = {}
PBMSGEMPTY.fields = {}
PBMSGEMPTY.is_extendable = false
PBMSGEMPTY.extensions = {}

PBMsgEmpty = protobuf.Message(PBMSGEMPTY)
PBMsgHead = protobuf.Message(PBMSGHEAD)

